/*
 * FrmMapa.java
 */
package pantallas;

import dtos.UsuarioDTO;
import dtos.DatosRutaDTO;
import dtos.LineaDTO;
import dtos.MapaDTO;
import dtos.RutaDTO;
import excepciones.MostrarMapaException;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
//import mostrarMapa.FacadeMostrarMapa;
//import mostrarMapa.IMostrarMapa;
//import excepciones.MostrarMapaException;
import org.jxmapviewer.viewer.WaypointPainter;
import excepciones.PresentacionException;
import implementaciones.MapaBO;
import implementaciones.MapaDAO;
import mostrarMapa.CtrlMostrarMapa;
import mostrarMapa.FacadeMostrarMapa;
import mostrarMapa.IMostrarMapa;
import utilidades.Validador;

/**
 * Clase que representa la pantalla donde aparece el mapa y el usuario puede
 * seleccionar la línea que desea ver.
 *
 * @author Eliana Monge Cámara - 00000247782
 * @author Francisco Valdez Gastelum - 00000246904
 * @author Diego Valenzuela Parra - 00000247700
 */
public class FrmMapa extends javax.swing.JFrame {

    private final IMostrarMapa facadeMostrarMapa;
    private MapaDTO mapa;
    private final UsuarioDTO usuario;

    /**
     * Constructor que inicializa los atributos de la clase.
     *
     * @param usuario Usuario que está logueado en el sistema.
     * @throws PresentacionException si ocurre un error a la hora de validar la
     * sesión o cuando se quiere mostrar el mapa.
     */
    public FrmMapa(UsuarioDTO usuario) throws PresentacionException {
        initComponents();

        this.usuario = usuario;
        this.facadeMostrarMapa = new FacadeMostrarMapa(new CtrlMostrarMapa(new MapaBO(new MapaDAO())));
        lblLinea.setVisible(false); // Escondemos el label donde sale la línea.

        // Mandamos a validar la sesión.
        Validador.validarSesion(usuario, this);

        // Mandamos a mostrar el mapa.
        mostrarMapa();
    }

    /**
     * Método para mostrar el mapa en la pantalla.
     *
     * @throws PresentacionException si ocurre un error a la hora de mostrar el
     * mapa.
     */
    private void mostrarMapa() throws PresentacionException {
        try {
            // Mandamos a cargar el mapa.
            mapa = facadeMostrarMapa.cargarMapa(pnlMapa);
        } catch (MostrarMapaException mme) {
            throw new PresentacionException(mme.getMessage());
        }
    }

    /**
     * Método para mostrar la ruta y las paradas de una línea seleccionada.
     *
     * @param numLinea Número de la línea que se quiere visualizar.
     */
    private void mostrarRuta(int numLinea) {
        // Evaluamos que los datos de la línea seleccionada existan.
        if (numLinea > mapa.getLineas().size()) {
            JOptionPane.showMessageDialog(this, "Por el momento no contamos con la ruta de esa línea. Inténtelo más tarde.", "¡Oops!", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Obtenemos la línea seleccionada y su respectiva ruta.
        LineaDTO linea = mapa.getLineas().get(numLinea - 1);
        RutaDTO ruta = linea.getRuta();

        // Mandamos a cargar los datos para construir la ruta.
        List<DatosRutaDTO> listaDatosRuta = facadeMostrarMapa.cargarRuta(ruta);

        // Inicializamos un nuevo WaypointPainter (pintor de puntos).
        WaypointPainter wp = new WaypointPainter();
        // Con esto asignamos las paradas a pintar en el mapa.
        wp.setWaypoints(linea.getParadas());

        // Asignamos un el WaypointPainter al panel donde se dibujará el mapa.
        pnlMapa.setOverlayPainter(wp);
        // Indicamos la lista con los datos de la ruta que se dibujará.
        pnlMapa.setListaDatosRuta(listaDatosRuta);

        // Imprimimos el número de la línea seleccionada.
        lblLinea.setText("Línea " + numLinea);
        lblLinea.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMapa = new utilidades.JXMapViewerCustom();
        jPanel2 = new javax.swing.JPanel();
        lblLinea = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        btnLinea1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnLinea2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnLinea3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnLinea4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnLinea5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnLinea6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnLinea7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btnLinea8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btnLinea9 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btnLinea10 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btnLinea11 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btnLinea12 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btnLinea13 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        btnLinea14 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        btnLinea15 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        lblAtnAlCliente = new javax.swing.JLabel();
        lblQuejas = new javax.swing.JLabel();
        lblMapa = new javax.swing.JLabel();
        lblCerrarSesion = new javax.swing.JLabel();
        lblHome = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1120, 690));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMapa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(79, 89, 144), 2));

        jPanel2.setBackground(new Color(79, 89, 144, 80));

        lblLinea.setBackground(new Color(79, 89, 144, 80));
        lblLinea.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblLinea.setForeground(new java.awt.Color(0, 0, 0));
        lblLinea.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLinea.setText(" ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLinea, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLinea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlMapaLayout = new javax.swing.GroupLayout(pnlMapa);
        pnlMapa.setLayout(pnlMapaLayout);
        pnlMapaLayout.setHorizontalGroup(
            pnlMapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMapaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(700, Short.MAX_VALUE))
        );
        pnlMapaLayout.setVerticalGroup(
            pnlMapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMapaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(450, Short.MAX_VALUE))
        );

        getContentPane().add(pnlMapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 850, 520));

        jScrollPane1.setForeground(new java.awt.Color(79, 89, 144));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLinea1.setBackground(new java.awt.Color(79, 89, 144));
        btnLinea1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLinea1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLinea1MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Línea 1");

        javax.swing.GroupLayout btnLinea1Layout = new javax.swing.GroupLayout(btnLinea1);
        btnLinea1.setLayout(btnLinea1Layout);
        btnLinea1Layout.setHorizontalGroup(
            btnLinea1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLinea1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnLinea1Layout.setVerticalGroup(
            btnLinea1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLinea1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(btnLinea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 60));

        btnLinea2.setBackground(new java.awt.Color(152, 165, 199));
        btnLinea2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLinea2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLinea2MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Línea 2");

        javax.swing.GroupLayout btnLinea2Layout = new javax.swing.GroupLayout(btnLinea2);
        btnLinea2.setLayout(btnLinea2Layout);
        btnLinea2Layout.setHorizontalGroup(
            btnLinea2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLinea2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnLinea2Layout.setVerticalGroup(
            btnLinea2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLinea2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(btnLinea2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 220, 60));

        btnLinea3.setBackground(new java.awt.Color(79, 89, 144));
        btnLinea3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLinea3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLinea3MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Línea 3");

        javax.swing.GroupLayout btnLinea3Layout = new javax.swing.GroupLayout(btnLinea3);
        btnLinea3.setLayout(btnLinea3Layout);
        btnLinea3Layout.setHorizontalGroup(
            btnLinea3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLinea3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnLinea3Layout.setVerticalGroup(
            btnLinea3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLinea3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(btnLinea3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 220, 60));

        btnLinea4.setBackground(new java.awt.Color(152, 165, 199));
        btnLinea4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLinea4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLinea4MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Línea 4");

        javax.swing.GroupLayout btnLinea4Layout = new javax.swing.GroupLayout(btnLinea4);
        btnLinea4.setLayout(btnLinea4Layout);
        btnLinea4Layout.setHorizontalGroup(
            btnLinea4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLinea4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnLinea4Layout.setVerticalGroup(
            btnLinea4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLinea4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(btnLinea4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 220, 60));

        btnLinea5.setBackground(new java.awt.Color(79, 89, 144));
        btnLinea5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLinea5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLinea5MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Línea 5");

        javax.swing.GroupLayout btnLinea5Layout = new javax.swing.GroupLayout(btnLinea5);
        btnLinea5.setLayout(btnLinea5Layout);
        btnLinea5Layout.setHorizontalGroup(
            btnLinea5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLinea5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnLinea5Layout.setVerticalGroup(
            btnLinea5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLinea5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(btnLinea5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 220, 70));

        btnLinea6.setBackground(new java.awt.Color(152, 165, 199));
        btnLinea6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLinea6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLinea6MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Línea 6");

        javax.swing.GroupLayout btnLinea6Layout = new javax.swing.GroupLayout(btnLinea6);
        btnLinea6.setLayout(btnLinea6Layout);
        btnLinea6Layout.setHorizontalGroup(
            btnLinea6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLinea6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnLinea6Layout.setVerticalGroup(
            btnLinea6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLinea6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(btnLinea6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 220, 70));

        btnLinea7.setBackground(new java.awt.Color(79, 89, 144));
        btnLinea7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLinea7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLinea7MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Línea 7");

        javax.swing.GroupLayout btnLinea7Layout = new javax.swing.GroupLayout(btnLinea7);
        btnLinea7.setLayout(btnLinea7Layout);
        btnLinea7Layout.setHorizontalGroup(
            btnLinea7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLinea7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnLinea7Layout.setVerticalGroup(
            btnLinea7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLinea7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(btnLinea7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 220, 70));

        btnLinea8.setBackground(new java.awt.Color(152, 165, 199));
        btnLinea8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLinea8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLinea8MouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Línea 8");

        javax.swing.GroupLayout btnLinea8Layout = new javax.swing.GroupLayout(btnLinea8);
        btnLinea8.setLayout(btnLinea8Layout);
        btnLinea8Layout.setHorizontalGroup(
            btnLinea8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLinea8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnLinea8Layout.setVerticalGroup(
            btnLinea8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLinea8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(btnLinea8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 220, 60));

        btnLinea9.setBackground(new java.awt.Color(79, 89, 144));
        btnLinea9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLinea9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLinea9MouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Línea 9");

        javax.swing.GroupLayout btnLinea9Layout = new javax.swing.GroupLayout(btnLinea9);
        btnLinea9.setLayout(btnLinea9Layout);
        btnLinea9Layout.setHorizontalGroup(
            btnLinea9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLinea9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnLinea9Layout.setVerticalGroup(
            btnLinea9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLinea9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(btnLinea9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 220, 60));

        btnLinea10.setBackground(new java.awt.Color(152, 165, 199));
        btnLinea10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLinea10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLinea10MouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Línea 10");

        javax.swing.GroupLayout btnLinea10Layout = new javax.swing.GroupLayout(btnLinea10);
        btnLinea10.setLayout(btnLinea10Layout);
        btnLinea10Layout.setHorizontalGroup(
            btnLinea10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLinea10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnLinea10Layout.setVerticalGroup(
            btnLinea10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLinea10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(btnLinea10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 220, 60));

        btnLinea11.setBackground(new java.awt.Color(79, 89, 144));
        btnLinea11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLinea11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLinea11MouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Línea 11");

        javax.swing.GroupLayout btnLinea11Layout = new javax.swing.GroupLayout(btnLinea11);
        btnLinea11.setLayout(btnLinea11Layout);
        btnLinea11Layout.setHorizontalGroup(
            btnLinea11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLinea11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnLinea11Layout.setVerticalGroup(
            btnLinea11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLinea11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(btnLinea11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 220, 60));

        btnLinea12.setBackground(new java.awt.Color(152, 165, 199));
        btnLinea12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLinea12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLinea12MouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Línea 12");

        javax.swing.GroupLayout btnLinea12Layout = new javax.swing.GroupLayout(btnLinea12);
        btnLinea12.setLayout(btnLinea12Layout);
        btnLinea12Layout.setHorizontalGroup(
            btnLinea12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLinea12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnLinea12Layout.setVerticalGroup(
            btnLinea12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLinea12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(btnLinea12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 690, 220, 60));

        btnLinea13.setBackground(new java.awt.Color(79, 89, 144));
        btnLinea13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLinea13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLinea13MouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Línea 13");

        javax.swing.GroupLayout btnLinea13Layout = new javax.swing.GroupLayout(btnLinea13);
        btnLinea13.setLayout(btnLinea13Layout);
        btnLinea13Layout.setHorizontalGroup(
            btnLinea13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLinea13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnLinea13Layout.setVerticalGroup(
            btnLinea13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLinea13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(btnLinea13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 750, 220, 60));

        btnLinea14.setBackground(new java.awt.Color(152, 165, 199));
        btnLinea14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLinea14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLinea14MouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Línea 14");

        javax.swing.GroupLayout btnLinea14Layout = new javax.swing.GroupLayout(btnLinea14);
        btnLinea14.setLayout(btnLinea14Layout);
        btnLinea14Layout.setHorizontalGroup(
            btnLinea14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLinea14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnLinea14Layout.setVerticalGroup(
            btnLinea14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLinea14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(btnLinea14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 810, 220, 60));

        btnLinea15.setBackground(new java.awt.Color(79, 89, 144));
        btnLinea15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLinea15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLinea15MouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Línea 15");

        javax.swing.GroupLayout btnLinea15Layout = new javax.swing.GroupLayout(btnLinea15);
        btnLinea15.setLayout(btnLinea15Layout);
        btnLinea15Layout.setHorizontalGroup(
            btnLinea15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLinea15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnLinea15Layout.setVerticalGroup(
            btnLinea15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLinea15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(btnLinea15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 870, 220, 60));

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 240, 520));

        lblAtnAlCliente.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblAtnAlCliente.setForeground(new java.awt.Color(0, 0, 0));
        lblAtnAlCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAtnAlCliente.setText("Atención al cliente");
        lblAtnAlCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAtnAlCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAtnAlClienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAtnAlClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAtnAlClienteMouseExited(evt);
            }
        });
        getContentPane().add(lblAtnAlCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, 210, 70));

        lblQuejas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblQuejas.setForeground(new java.awt.Color(0, 0, 0));
        lblQuejas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuejas.setText("Quejas");
        lblQuejas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblQuejas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQuejasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblQuejasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblQuejasMouseExited(evt);
            }
        });
        getContentPane().add(lblQuejas, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, 90, 70));

        lblMapa.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblMapa.setForeground(new java.awt.Color(0, 0, 0));
        lblMapa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMapa.setText("Mapa");
        lblMapa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMapa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMapaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMapaMouseExited(evt);
            }
        });
        getContentPane().add(lblMapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 90, 70));

        lblCerrarSesion.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCerrarSesion.setForeground(new java.awt.Color(0, 0, 0));
        lblCerrarSesion.setText("       Cerrar sesión");
        lblCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCerrarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCerrarSesionMouseExited(evt);
            }
        });
        getContentPane().add(lblCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 30, 200, 90));

        lblHome.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblHome.setForeground(new java.awt.Color(0, 0, 0));
        lblHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHomeMouseClicked(evt);
            }
        });
        getContentPane().add(lblHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 220, 100));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.png"))); // NOI18N
        fondo.setText("jLabel17");
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 690));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método que reacciona al evento de dar clic en el botón para que se
     * muestre la ruta de la línea 1.
     *
     * @param evt Evento al que se escucha.
     */
    private void btnLinea1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLinea1MouseClicked
        mostrarRuta(1);
    }//GEN-LAST:event_btnLinea1MouseClicked

    /**
     * Método que reacciona al evento de dar clic en el botón para que se
     * muestre la ruta de la línea 2.
     *
     * @param evt Evento al que se escucha.
     */
    private void btnLinea2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLinea2MouseClicked
        mostrarRuta(2);
    }//GEN-LAST:event_btnLinea2MouseClicked

    /**
     * Método que reacciona al evento de dar clic en el botón para que se
     * muestre la ruta de la línea 3.
     *
     * @param evt Evento al que se escucha.
     */
    private void btnLinea3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLinea3MouseClicked
        mostrarRuta(3);
    }//GEN-LAST:event_btnLinea3MouseClicked

    /**
     * Método que reacciona al evento de dar clic en el botón para que se
     * muestre la ruta de la línea 4.
     *
     * @param evt Evento al que se escucha.
     */
    private void btnLinea4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLinea4MouseClicked
        mostrarRuta(4);
    }//GEN-LAST:event_btnLinea4MouseClicked

    /**
     * Método que reacciona al evento de dar clic en el botón para que se
     * muestre la ruta de la línea 5.
     *
     * @param evt Evento al que se escucha.
     */
    private void btnLinea5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLinea5MouseClicked
        mostrarRuta(5);
    }//GEN-LAST:event_btnLinea5MouseClicked

    /**
     * Método que reacciona al evento de dar clic en el botón para que se
     * muestre la ruta de la línea 6.
     *
     * @param evt Evento al que se escucha.
     */
    private void btnLinea6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLinea6MouseClicked
        mostrarRuta(6);
    }//GEN-LAST:event_btnLinea6MouseClicked

    /**
     * Método que reacciona al evento de dar clic en el botón para que se
     * muestre la ruta de la línea 7.
     *
     * @param evt Evento al que se escucha.
     */
    private void btnLinea7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLinea7MouseClicked
        mostrarRuta(7);
    }//GEN-LAST:event_btnLinea7MouseClicked

    /**
     * Método que reacciona al evento de dar clic en el botón para que se
     * muestre la ruta de la línea 8.
     *
     * @param evt Evento al que se escucha.
     */
    private void btnLinea8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLinea8MouseClicked
        mostrarRuta(8);
    }//GEN-LAST:event_btnLinea8MouseClicked

    /**
     * Método que reacciona al evento de dar clic en el botón para que se
     * muestre la ruta de la línea 9.
     *
     * @param evt Evento al que se escucha.
     */
    private void btnLinea9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLinea9MouseClicked
        mostrarRuta(9);
    }//GEN-LAST:event_btnLinea9MouseClicked

    /**
     * Método que reacciona al evento de dar clic en el botón para que se
     * muestre la ruta de la línea 10.
     *
     * @param evt Evento al que se escucha.
     */
    private void btnLinea10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLinea10MouseClicked
        mostrarRuta(10);
    }//GEN-LAST:event_btnLinea10MouseClicked

    /**
     * Método que reacciona al evento de dar clic en el botón para que se
     * muestre la ruta de la línea 11.
     *
     * @param evt Evento al que se escucha.
     */
    private void btnLinea11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLinea11MouseClicked
        mostrarRuta(11);
    }//GEN-LAST:event_btnLinea11MouseClicked

    /**
     * Método que reacciona al evento de dar clic en el botón para que se
     * muestre la ruta de la línea 12.
     *
     * @param evt Evento al que se escucha.
     */
    private void btnLinea12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLinea12MouseClicked
        mostrarRuta(12);
    }//GEN-LAST:event_btnLinea12MouseClicked

    /**
     * Método que reacciona al evento de dar clic en el botón para que se
     * muestre la ruta de la línea 13.
     *
     * @param evt Evento al que se escucha.
     */
    private void btnLinea13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLinea13MouseClicked
        mostrarRuta(13);
    }//GEN-LAST:event_btnLinea13MouseClicked

    /**
     * Método que reacciona al evento de dar clic en el botón para que se
     * muestre la ruta de la línea 14.
     *
     * @param evt Evento al que se escucha.
     */
    private void btnLinea14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLinea14MouseClicked
        mostrarRuta(14);
    }//GEN-LAST:event_btnLinea14MouseClicked

    /**
     * Método que reacciona al evento de dar clic en el botón para que se
     * muestre la ruta de la línea 15.
     *
     * @param evt Evento al que se escucha.
     */
    private void btnLinea15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLinea15MouseClicked
        mostrarRuta(15);
    }//GEN-LAST:event_btnLinea15MouseClicked

    /**
     * Método que reacciona al evento de dar clic en el botón para cerrar
     * sesión. Devuelve al usuario al login.
     *
     * @param evt Evento al que se escucha.
     */
    private void lblCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarSesionMouseClicked
        FrmLogin frmLogin = new FrmLogin();
        frmLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblCerrarSesionMouseClicked

    /**
     * Método que reacciona al evento de pasar el mouse por encima del botón de
     * cerrar sesión y cambiar su color.
     *
     * @param evt Evento al que se escucha
     */
    private void lblCerrarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarSesionMouseEntered
        lblCerrarSesion.setForeground(Color.GRAY);
    }//GEN-LAST:event_lblCerrarSesionMouseEntered

    /**
     * Método que reacciona al evento de que el mouse ya no esté sobre el botón
     * de cerrar sesión y cambiar su color.
     *
     * @param evt Evento al que se escucha
     */
    private void lblCerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarSesionMouseExited
        lblCerrarSesion.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblCerrarSesionMouseExited

    /**
     * Método que reacciona al evento de dar clic en el botón para ir a la
     * pantalla principal.
     *
     * @param evt Evento al que se escucha.
     */
    private void lblHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseClicked
        try {
            FrmHomeCliente frmHome = new FrmHomeCliente(usuario);
            frmHome.setVisible(true);
        } catch (PresentacionException pe) {
            // Se muestra un mensaje si no se validó la sesión.
            JOptionPane.showMessageDialog(this, pe.getMessage(), "¡Error!", JOptionPane.ERROR_MESSAGE);
        }
        this.dispose();
    }//GEN-LAST:event_lblHomeMouseClicked

    /**
     * Método que reacciona al evento de pasar el mouse por encima del botón de
     * atención al cliente y cambiar su color.
     *
     * @param evt Evento al que se escucha
     */
    private void lblAtnAlClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAtnAlClienteMouseEntered
        lblAtnAlCliente.setForeground(Color.GRAY);
    }//GEN-LAST:event_lblAtnAlClienteMouseEntered

    /**
     * Método que reacciona al evento de que el mouse ya no esté sobre el botón
     * de atención al cliente y cambiar su color.
     *
     * @param evt Evento al que se escucha
     */
    private void lblAtnAlClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAtnAlClienteMouseExited
        lblAtnAlCliente.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblAtnAlClienteMouseExited

    /**
     * Método que reacciona al evento de dar clic en el botón para mandar
     * quejas.
     *
     * @param evt Evento al que se escucha.
     */
    private void lblQuejasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuejasMouseClicked
        try {
            FrmQuejas frmQuejas = new FrmQuejas(usuario);
            frmQuejas.setVisible(true);
        } catch (PresentacionException pe) {
            JOptionPane.showMessageDialog(this, pe.getMessage(), "¡Error!", JOptionPane.ERROR_MESSAGE);
        }
        this.dispose();
    }//GEN-LAST:event_lblQuejasMouseClicked

    /**
     * Método que reacciona al evento de pasar el mouse por encima del botón de
     * quejas y cambiar su color.
     *
     * @param evt Evento al que se escucha
     */
    private void lblQuejasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuejasMouseEntered
        lblQuejas.setForeground(Color.GRAY);
    }//GEN-LAST:event_lblQuejasMouseEntered

    /**
     * Método que reacciona al evento de que el mouse ya no esté sobre el botón
     * de quejas y cambiar su color.
     *
     * @param evt Evento al que se escucha
     */
    private void lblQuejasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuejasMouseExited
        lblQuejas.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblQuejasMouseExited

    /**
     * Método que reacciona al evento de pasar el mouse por encima del botón del
     * mapa y cambiar su color.
     *
     * @param evt Evento al que se escucha
     */
    private void lblMapaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMapaMouseEntered
        lblMapa.setForeground(Color.GRAY);
    }//GEN-LAST:event_lblMapaMouseEntered

    /**
     * Método que reacciona al evento de que el mouse ya no esté sobre el botón
     * del mapa y cambiar su color.
     *
     * @param evt Evento al que se escucha
     */
    private void lblMapaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMapaMouseExited
        lblMapa.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblMapaMouseExited

    /**
     * Método que reacciona al evento de dar clic en el botón para abrir el
     * módulo de atención al cliente.
     *
     * @param evt Evento al que se escucha.
     */
    private void lblAtnAlClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAtnAlClienteMouseClicked
        try {
            FrmAtnVistaCliente frmAtnVistaCliente = new FrmAtnVistaCliente(usuario);
            frmAtnVistaCliente.setVisible(true);
        } catch (PresentacionException pe) {
            JOptionPane.showMessageDialog(this, pe.getMessage(), "¡Error!", JOptionPane.ERROR_MESSAGE);
        }
        this.dispose();
    }//GEN-LAST:event_lblAtnAlClienteMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnLinea1;
    private javax.swing.JPanel btnLinea10;
    private javax.swing.JPanel btnLinea11;
    private javax.swing.JPanel btnLinea12;
    private javax.swing.JPanel btnLinea13;
    private javax.swing.JPanel btnLinea14;
    private javax.swing.JPanel btnLinea15;
    private javax.swing.JPanel btnLinea2;
    private javax.swing.JPanel btnLinea3;
    private javax.swing.JPanel btnLinea4;
    private javax.swing.JPanel btnLinea5;
    private javax.swing.JPanel btnLinea6;
    private javax.swing.JPanel btnLinea7;
    private javax.swing.JPanel btnLinea8;
    private javax.swing.JPanel btnLinea9;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAtnAlCliente;
    private javax.swing.JLabel lblCerrarSesion;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblLinea;
    private javax.swing.JLabel lblMapa;
    private javax.swing.JLabel lblQuejas;
    private utilidades.JXMapViewerCustom pnlMapa;
    // End of variables declaration//GEN-END:variables

}
