/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas;

import dtos.CamionDTO;
import dtos.UsuarioDTO;
import excepciones.PresentacionException;
import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.temporal.ChronoUnit;
import java.util.Date;
import javax.swing.JOptionPane;
import programarMantenimiento.FacadeProgramarMantenimiento;
import programarMantenimiento.IProgramarMantenimiento;
import programarMantenimiento.ProgramarMantenimientoException;
import utilidades.Validador;

/**
 *
 * @author elimo
 */
public class FrmProgramarMantenimiento extends javax.swing.JFrame {

    private final IProgramarMantenimiento programarMantenimiento;
    private UsuarioDTO usuario;
    private CamionDTO camion;

    /**
     * Creates new form FrmProgramarMantenimiento
     */
    public FrmProgramarMantenimiento(UsuarioDTO usuario) throws PresentacionException {
        initComponents();
        programarMantenimiento = new FacadeProgramarMantenimiento();
        this.usuario = usuario;
        camion = new CamionDTO();

        Validador.validarSesion(usuario, this);

        switch (usuario.getTipo()) {
            case "PPMM":
                lblMantenimiento.setVisible(true);
                break;
            case "GERE":
                lblQuejas.setVisible(true);
                lblAtnCliente.setVisible(true);
                lblMantenimiento1.setVisible(true);
                break;
        }
    }

    private void seleccionarUnidad(String numero) {
        try {
            LocalDate fechaHoy = LocalDate.now();
            camion = programarMantenimiento.obtenerPorNumeroUnidad(numero);
            LocalDate fechaUltimoMantenimiento = camion.getFechaUltimoMantenimiento().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

            long mesesDesdeUltimoMantenimiento = ChronoUnit.MONTHS.between(fechaUltimoMantenimiento, fechaHoy);
            if (mesesDesdeUltimoMantenimiento >= 2) {
                programarMantenimiento.actualizarEstado(camion.getNumeroUnidad(), "MALO", "MALO", "MALO", "MALO");
                programarMantenimiento.actualizarPrioridadYFechaMantenimiento(camion.getNumeroUnidad(), "ALTO", camion.getFechaUltimoMantenimiento());
                camion = programarMantenimiento.obtenerPorNumeroUnidad(numero);

            }
            if (mesesDesdeUltimoMantenimiento == 1) {
                programarMantenimiento.actualizarEstado(camion.getNumeroUnidad(), "MEDIO", "MEDIO", "MEDIO", "MEDIO");
                programarMantenimiento.actualizarPrioridadYFechaMantenimiento(camion.getNumeroUnidad(), "MEDIO", camion.getFechaUltimoMantenimiento());

                camion = programarMantenimiento.obtenerPorNumeroUnidad(numero);
            }
            lblLimpieza.setText(camion.getEstadoLimpieza().toUpperCase());
            FacadeProgramarMantenimiento.actualizarLabelConEstado(lblLimpieza, lblLimpieza.getText(), lblLlanta, lblLimpieza.getText(), lblLuces, lblLimpieza.getText(),lblMotor, lblLimpieza.getText());
            lblPrioridad.setText(camion.getNivelPrioridad().toUpperCase());
            FacadeProgramarMantenimiento.updatePrioridadLabel(lblPrioridad.getText().toUpperCase(), lblPrioridad);
            txtUnidad.setText("Estas visualizando la unidad "+camion.getNumeroUnidad());
        } catch (ProgramarMantenimientoException pme) {
            JOptionPane.showMessageDialog(this, pme.getMessage(), "¡Error!", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblHome = new javax.swing.JLabel();
        lblCerrarSesion = new javax.swing.JLabel();
        lblQuejas = new javax.swing.JLabel();
        lblAtnCliente = new javax.swing.JLabel();
        lblMantenimiento = new javax.swing.JLabel();
        lblMantenimiento1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        btnUnidad001 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnUnidad002 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnUnidad003 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnUnidad004 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnUnidad005 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnUnidad006 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnUnidad007 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btnUnidad008 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btnUnidad009 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btnUnidad010 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblLimpieza = new javax.swing.JLabel();
        lblMotor = new javax.swing.JLabel();
        lblLlanta = new javax.swing.JLabel();
        lblLuces = new javax.swing.JLabel();
        lblFechaMantenimiento = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lblPrioridad = new javax.swing.JLabel();
        txtUnidad = new javax.swing.JLabel();
        img = new javax.swing.JLabel();
        btnLlanta = new javax.swing.JButton();
        btnMotor = new javax.swing.JButton();
        btnLuces = new javax.swing.JButton();
        btnLimpieza = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHome.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHomeMouseClicked(evt);
            }
        });
        jPanel1.add(lblHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 220, 100));

        lblCerrarSesion.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCerrarSesion.setText("Cerrar sesión");
        lblCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCerrarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCerrarSesionMouseExited(evt);
            }
        });
        jPanel1.add(lblCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 40, -1, 90));

        lblQuejas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblQuejas.setText("Ver quejas");
        lblQuejas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblQuejas.setPreferredSize(null);
        lblQuejas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQuejasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblQuejasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblQuejasMouseExited(evt);
            }
        });
        lblQuejas.setVisible(false);
        jPanel1.add(lblQuejas, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, -1, 90));

        lblAtnCliente.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblAtnCliente.setText("Atención al cliente");
        lblAtnCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAtnCliente.setPreferredSize(null);
        lblAtnCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAtnClienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAtnClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAtnClienteMouseExited(evt);
            }
        });
        lblAtnCliente.setVisible(false);
        jPanel1.add(lblAtnCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, -1, 90));

        lblMantenimiento.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblMantenimiento.setText("Mantenimiento");
        lblMantenimiento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMantenimiento.setPreferredSize(null);
        lblMantenimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMantenimientoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMantenimientoMouseExited(evt);
            }
        });
        lblMantenimiento.setVisible(false);
        jPanel1.add(lblMantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, -1, 90));

        lblMantenimiento1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblMantenimiento1.setText("Mantenimiento");
        lblMantenimiento1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMantenimiento1.setPreferredSize(null);
        lblMantenimiento1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMantenimiento1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMantenimiento1MouseExited(evt);
            }
        });
        lblMantenimiento1.setVisible(false);
        jPanel1.add(lblMantenimiento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 40, -1, 90));

        jScrollPane1.setForeground(new java.awt.Color(79, 89, 144));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUnidad001.setBackground(new java.awt.Color(79, 89, 144));
        btnUnidad001.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUnidad001.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUnidad001MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Unidad #001");

        javax.swing.GroupLayout btnUnidad001Layout = new javax.swing.GroupLayout(btnUnidad001);
        btnUnidad001.setLayout(btnUnidad001Layout);
        btnUnidad001Layout.setHorizontalGroup(
            btnUnidad001Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnUnidad001Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnUnidad001Layout.setVerticalGroup(
            btnUnidad001Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnUnidad001Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(btnUnidad001, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 60));

        btnUnidad002.setBackground(new java.awt.Color(152, 165, 199));
        btnUnidad002.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUnidad002.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUnidad002MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Unidad #002");

        javax.swing.GroupLayout btnUnidad002Layout = new javax.swing.GroupLayout(btnUnidad002);
        btnUnidad002.setLayout(btnUnidad002Layout);
        btnUnidad002Layout.setHorizontalGroup(
            btnUnidad002Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnUnidad002Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnUnidad002Layout.setVerticalGroup(
            btnUnidad002Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnUnidad002Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(btnUnidad002, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 410, 60));

        btnUnidad003.setBackground(new java.awt.Color(79, 89, 144));
        btnUnidad003.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUnidad003.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUnidad003MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Unidad #003");

        javax.swing.GroupLayout btnUnidad003Layout = new javax.swing.GroupLayout(btnUnidad003);
        btnUnidad003.setLayout(btnUnidad003Layout);
        btnUnidad003Layout.setHorizontalGroup(
            btnUnidad003Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnUnidad003Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnUnidad003Layout.setVerticalGroup(
            btnUnidad003Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnUnidad003Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(btnUnidad003, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 410, 60));

        btnUnidad004.setBackground(new java.awt.Color(152, 165, 199));
        btnUnidad004.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUnidad004.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUnidad004MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Unidad #004");

        javax.swing.GroupLayout btnUnidad004Layout = new javax.swing.GroupLayout(btnUnidad004);
        btnUnidad004.setLayout(btnUnidad004Layout);
        btnUnidad004Layout.setHorizontalGroup(
            btnUnidad004Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnUnidad004Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnUnidad004Layout.setVerticalGroup(
            btnUnidad004Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnUnidad004Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(btnUnidad004, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 410, 60));

        btnUnidad005.setBackground(new java.awt.Color(79, 89, 144));
        btnUnidad005.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUnidad005.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUnidad005MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Unidad #005");

        javax.swing.GroupLayout btnUnidad005Layout = new javax.swing.GroupLayout(btnUnidad005);
        btnUnidad005.setLayout(btnUnidad005Layout);
        btnUnidad005Layout.setHorizontalGroup(
            btnUnidad005Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnUnidad005Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnUnidad005Layout.setVerticalGroup(
            btnUnidad005Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnUnidad005Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(btnUnidad005, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 410, 70));

        btnUnidad006.setBackground(new java.awt.Color(152, 165, 199));
        btnUnidad006.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUnidad006.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUnidad006MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Unidad #006");

        javax.swing.GroupLayout btnUnidad006Layout = new javax.swing.GroupLayout(btnUnidad006);
        btnUnidad006.setLayout(btnUnidad006Layout);
        btnUnidad006Layout.setHorizontalGroup(
            btnUnidad006Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnUnidad006Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnUnidad006Layout.setVerticalGroup(
            btnUnidad006Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnUnidad006Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(btnUnidad006, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 410, 70));

        btnUnidad007.setBackground(new java.awt.Color(79, 89, 144));
        btnUnidad007.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUnidad007.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUnidad007MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Unidad #007");

        javax.swing.GroupLayout btnUnidad007Layout = new javax.swing.GroupLayout(btnUnidad007);
        btnUnidad007.setLayout(btnUnidad007Layout);
        btnUnidad007Layout.setHorizontalGroup(
            btnUnidad007Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnUnidad007Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnUnidad007Layout.setVerticalGroup(
            btnUnidad007Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnUnidad007Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(btnUnidad007, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 410, 70));

        btnUnidad008.setBackground(new java.awt.Color(152, 165, 199));
        btnUnidad008.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUnidad008.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUnidad008MouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Unidad #008");

        javax.swing.GroupLayout btnUnidad008Layout = new javax.swing.GroupLayout(btnUnidad008);
        btnUnidad008.setLayout(btnUnidad008Layout);
        btnUnidad008Layout.setHorizontalGroup(
            btnUnidad008Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnUnidad008Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnUnidad008Layout.setVerticalGroup(
            btnUnidad008Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnUnidad008Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(btnUnidad008, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 410, 60));

        btnUnidad009.setBackground(new java.awt.Color(79, 89, 144));
        btnUnidad009.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUnidad009.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUnidad009MouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Unidad #009");

        javax.swing.GroupLayout btnUnidad009Layout = new javax.swing.GroupLayout(btnUnidad009);
        btnUnidad009.setLayout(btnUnidad009Layout);
        btnUnidad009Layout.setHorizontalGroup(
            btnUnidad009Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnUnidad009Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnUnidad009Layout.setVerticalGroup(
            btnUnidad009Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnUnidad009Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(btnUnidad009, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 410, 60));

        btnUnidad010.setBackground(new java.awt.Color(152, 165, 199));
        btnUnidad010.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUnidad010.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUnidad010MouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Unidad #010");

        javax.swing.GroupLayout btnUnidad010Layout = new javax.swing.GroupLayout(btnUnidad010);
        btnUnidad010.setLayout(btnUnidad010Layout);
        btnUnidad010Layout.setHorizontalGroup(
            btnUnidad010Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnUnidad010Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnUnidad010Layout.setVerticalGroup(
            btnUnidad010Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnUnidad010Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(btnUnidad010, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 410, 60));

        jScrollPane1.setViewportView(jPanel2);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 190, 420, 470));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Estado motor");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 110, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Estado llanta");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 490, 110, 20));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("Estado luces");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 490, 110, 20));

        lblLimpieza.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblLimpieza.setForeground(new java.awt.Color(0, 102, 0));
        jPanel1.add(lblLimpieza, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 110, 30));

        lblMotor.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblMotor.setForeground(new java.awt.Color(0, 102, 0));
        jPanel1.add(lblMotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 90, 30));

        lblLlanta.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblLlanta.setForeground(new java.awt.Color(0, 102, 0));
        jPanel1.add(lblLlanta, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 510, 100, 40));

        lblLuces.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblLuces.setForeground(new java.awt.Color(0, 102, 0));
        jPanel1.add(lblLuces, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 510, 90, 30));

        lblFechaMantenimiento.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblFechaMantenimiento.setText("09/05/2024");
        lblFechaMantenimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFechaMantenimientoMouseClicked(evt);
            }
        });
        jPanel1.add(lblFechaMantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 610, 260, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel19.setText("Estado limpieza");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 190, -1));

        lblPrioridad.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblPrioridad.setForeground(new java.awt.Color(0, 102, 0));
        jPanel1.add(lblPrioridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 610, 160, 50));

        txtUnidad.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel1.add(txtUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 290, 20));

        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Group 19 (1).png"))); // NOI18N
        jPanel1.add(img, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 690));

        btnLlanta.setText("jButton1");
        btnLlanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLlantaActionPerformed(evt);
            }
        });
        jPanel1.add(btnLlanta, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, 70, 70));

        btnMotor.setText("jButton1");
        btnMotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMotorActionPerformed(evt);
            }
        });
        jPanel1.add(btnMotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 70, 70));

        btnLuces.setText("jButton1");
        btnLuces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLucesActionPerformed(evt);
            }
        });
        jPanel1.add(btnLuces, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 490, 60, 70));

        btnLimpieza.setText("jButton1");
        btnLimpieza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiezaActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpieza, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 70, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiezaActionPerformed
        // TODO add your handling code here:
        FacadeProgramarMantenimiento.actualizarLabelEstado(lblLimpieza);
    }//GEN-LAST:event_btnLimpiezaActionPerformed

    private void btnLucesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLucesActionPerformed
        // TODO add your handling code here:
        FacadeProgramarMantenimiento.actualizarLabelEstado(lblLuces);
    }//GEN-LAST:event_btnLucesActionPerformed

    private void btnMotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMotorActionPerformed
        // TODO add your handling code here:
        FacadeProgramarMantenimiento.actualizarLabelEstado(lblMotor);
    }//GEN-LAST:event_btnMotorActionPerformed

    private void btnLlantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLlantaActionPerformed
        // TODO add your handling code here:
        FacadeProgramarMantenimiento.actualizarLabelEstado(lblLlanta);
    }//GEN-LAST:event_btnLlantaActionPerformed

    private void lblFechaMantenimientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFechaMantenimientoMouseClicked
        // TODO add your handling code here:
        try {
            programarMantenimiento.actualizarEstado(camion.getNumeroUnidad(), lblMotor.getText(), lblLimpieza.getText(), lblLlanta.getText(), lblLuces.getText());

            Date fecha = new Date();
            SimpleDateFormat sdf = new SimpleDateFormat("dd/yyyy/MM");
            String fechaFormateada = sdf.format(fecha);
            camion = programarMantenimiento.obtenerPorNumeroUnidad(camion.getNumeroUnidad());
            String prioridad = FacadeProgramarMantenimiento.calcularPrioridad(camion);
            programarMantenimiento.actualizarPrioridadYFechaMantenimiento(camion.getNumeroUnidad(), prioridad, sdf.parse(fechaFormateada));
            lblPrioridad.setText(prioridad);
            FacadeProgramarMantenimiento.updatePrioridadLabel(prioridad, lblPrioridad);

            lblFechaMantenimiento.setText(fechaFormateada);
        } catch (ProgramarMantenimientoException | ParseException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "¡Error!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_lblFechaMantenimientoMouseClicked

    private void btnUnidad010MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUnidad010MouseClicked
        seleccionarUnidad("010");
    }//GEN-LAST:event_btnUnidad010MouseClicked

    private void btnUnidad009MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUnidad009MouseClicked
        seleccionarUnidad("009");
    }//GEN-LAST:event_btnUnidad009MouseClicked

    private void btnUnidad008MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUnidad008MouseClicked
        seleccionarUnidad("008");
    }//GEN-LAST:event_btnUnidad008MouseClicked

    private void btnUnidad007MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUnidad007MouseClicked
        seleccionarUnidad("007");
    }//GEN-LAST:event_btnUnidad007MouseClicked

    private void btnUnidad006MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUnidad006MouseClicked
        seleccionarUnidad("006");
    }//GEN-LAST:event_btnUnidad006MouseClicked

    private void btnUnidad005MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUnidad005MouseClicked
        seleccionarUnidad("005");
    }//GEN-LAST:event_btnUnidad005MouseClicked

    private void btnUnidad004MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUnidad004MouseClicked
        seleccionarUnidad("004");
    }//GEN-LAST:event_btnUnidad004MouseClicked

    private void btnUnidad003MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUnidad003MouseClicked
        seleccionarUnidad("003");
    }//GEN-LAST:event_btnUnidad003MouseClicked

    private void btnUnidad002MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUnidad002MouseClicked
        seleccionarUnidad("002");
    }//GEN-LAST:event_btnUnidad002MouseClicked

    private void btnUnidad001MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUnidad001MouseClicked
        seleccionarUnidad("001");
    }//GEN-LAST:event_btnUnidad001MouseClicked

    /**
     * Método que reacciona al evento de dar clic en el botón para cerrar
     * sesión. Devuelve al usuario al login.
     *
     * @param evt Evento al que se escucha.
     */
    private void lblCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarSesionMouseClicked
        FrmLogin frmLogin = new FrmLogin();
        frmLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblCerrarSesionMouseClicked

    /**
     * Método que reacciona al evento de pasar el mouse por encima del botón de
     * cerrar sesión y cambiar su color.
     *
     * @param evt Evento al que se escucha
     */
    private void lblCerrarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarSesionMouseEntered
        lblCerrarSesion.setForeground(Color.GRAY);
    }//GEN-LAST:event_lblCerrarSesionMouseEntered

    /**
     * Método que reacciona al evento de que el mouse ya no esté sobre el botón
     * de cerrar sesión y cambiar su color.
     *
     * @param evt Evento al que se escucha
     */
    private void lblCerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarSesionMouseExited
        lblCerrarSesion.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblCerrarSesionMouseExited

    /**
     * Método que reacciona al evento de dar clic en el botón para visualizar
     * quejas.
     *
     * @param evt Evento al que se escucha.
     */
    private void lblQuejasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuejasMouseClicked
        try {
            FrmVisualizarQuejas frmAtnAlCliente = new FrmVisualizarQuejas(usuario);
            frmAtnAlCliente.setVisible(true);
        } catch (PresentacionException pe) {
            // Se muestra un mensaje si no se validó la sesión.
            JOptionPane.showMessageDialog(this, pe.getMessage(), "¡Error!", JOptionPane.ERROR_MESSAGE);
        }
        this.dispose();
    }//GEN-LAST:event_lblQuejasMouseClicked

    /**
     * Método que reacciona al evento de pasar el mouse por encima del botón de
     * quejas y cambiar su color.
     *
     * @param evt Evento al que se escucha
     */
    private void lblQuejasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuejasMouseEntered
        lblQuejas.setForeground(Color.GRAY);
    }//GEN-LAST:event_lblQuejasMouseEntered
    
    /**
     * Método que reacciona al evento de que el mouse ya no esté sobre el botón
     * de quejas y cambiar su color.
     *
     * @param evt Evento al que se escucha
     */
    private void lblQuejasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuejasMouseExited
        lblQuejas.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblQuejasMouseExited

    /**
     * Método que reacciona al evento de dar clic en el botón para el módulo de
     * atención al cliente.
     *
     * @param evt Evento al que se escucha.
     */
    private void lblAtnClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAtnClienteMouseClicked
        try {
            FrmAtnVistaTrabajador frmAtnAlCliente = new FrmAtnVistaTrabajador(usuario);
            frmAtnAlCliente.setVisible(true);
        } catch (PresentacionException pe) {
            // Se muestra un mensaje si no se validó la sesión.
            JOptionPane.showMessageDialog(this, pe.getMessage(), "¡Error!", JOptionPane.ERROR_MESSAGE);
        }
        this.dispose();
    }//GEN-LAST:event_lblAtnClienteMouseClicked

    /**
     * Método que reacciona al evento de pasar el mouse por encima del botón de
     * atención al cliente y cambiar su color.
     *
     * @param evt Evento al que se escucha
     */
    private void lblAtnClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAtnClienteMouseEntered
        lblAtnCliente.setForeground(Color.GRAY);
    }//GEN-LAST:event_lblAtnClienteMouseEntered

    /**
     * Método que reacciona al evento de que el mouse ya no esté sobre el botón
     * de atención al cliente y cambiar su color.
     *
     * @param evt Evento al que se escucha
     */
    private void lblAtnClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAtnClienteMouseExited
        lblAtnCliente.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblAtnClienteMouseExited

    /**
     * Método que reacciona al evento de pasar el mouse por encima del botón de
     * programar mantenimiento y cambiar su color.
     *
     * @param evt Evento al que se escucha
     */
    private void lblMantenimientoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMantenimientoMouseEntered
        lblMantenimiento.setForeground(Color.GRAY);
    }//GEN-LAST:event_lblMantenimientoMouseEntered

    /**
     * Método que reacciona al evento de que el mouse ya no esté sobre el botón
     * de programar mantenimiento y cambiar su color.
     *
     * @param evt Evento al que se escucha
     */
    private void lblMantenimientoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMantenimientoMouseExited
        lblMantenimiento.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblMantenimientoMouseExited

    /**
     * Método que reacciona al evento de pasar el mouse por encima del botón de
     * programar mantenimiento y cambiar su color.
     *
     * @param evt Evento al que se escucha
     */
    private void lblMantenimiento1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMantenimiento1MouseEntered
        lblMantenimiento1.setForeground(Color.GRAY);
    }//GEN-LAST:event_lblMantenimiento1MouseEntered

    /**
     * Método que reacciona al evento de que el mouse ya no esté sobre el botón
     * de programar mantenimiento y cambiar su color.
     *
     * @param evt Evento al que se escucha
     */
    private void lblMantenimiento1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMantenimiento1MouseExited
        lblMantenimiento1.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblMantenimiento1MouseExited

    /**
     * Método que reacciona al evento de dar clic en el botón para ir a la
     * pantalla principal.
     *
     * @param evt Evento al que se escucha.
     */
    private void lblHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseClicked
        try {
            FrmHomeTrabajador frmHome = new FrmHomeTrabajador(usuario);
            frmHome.setVisible(true);
        } catch (PresentacionException pe) {
            JOptionPane.showMessageDialog(this, pe.getMessage(), "¡Error!", JOptionPane.ERROR_MESSAGE);
        }
        this.dispose();
    }//GEN-LAST:event_lblHomeMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpieza;
    private javax.swing.JButton btnLlanta;
    private javax.swing.JButton btnLuces;
    private javax.swing.JButton btnMotor;
    private javax.swing.JPanel btnUnidad001;
    private javax.swing.JPanel btnUnidad002;
    private javax.swing.JPanel btnUnidad003;
    private javax.swing.JPanel btnUnidad004;
    private javax.swing.JPanel btnUnidad005;
    private javax.swing.JPanel btnUnidad006;
    private javax.swing.JPanel btnUnidad007;
    private javax.swing.JPanel btnUnidad008;
    private javax.swing.JPanel btnUnidad009;
    private javax.swing.JPanel btnUnidad010;
    private javax.swing.JLabel img;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAtnCliente;
    private javax.swing.JLabel lblCerrarSesion;
    private javax.swing.JLabel lblFechaMantenimiento;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblLimpieza;
    private javax.swing.JLabel lblLlanta;
    private javax.swing.JLabel lblLuces;
    private javax.swing.JLabel lblMantenimiento;
    private javax.swing.JLabel lblMantenimiento1;
    private javax.swing.JLabel lblMotor;
    private javax.swing.JLabel lblPrioridad;
    private javax.swing.JLabel lblQuejas;
    private javax.swing.JLabel txtUnidad;
    // End of variables declaration//GEN-END:variables
}
