/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas;

import dtos.UsuarioDTO;
import excepciones.PresentacionException;
import excepciones.RegistrarEmpleadoException;
import java.awt.Color;
import javax.swing.JOptionPane;
import registrarEmpleado.FacadeRegistrarEmpleado;
import registrarEmpleado.IRegistrarEmpleado;
import utilidades.Validador;

/**
 *
 * @author franc
 */
public class FrmRegistroTrabajador extends javax.swing.JFrame {

    private final IRegistrarEmpleado facadeRegistrarEmpleado;
    private UsuarioDTO usuario;

    /**
     * Creates new form FrmRegistrarEmpleado
     */
    public FrmRegistroTrabajador(UsuarioDTO usuario) throws PresentacionException {
        initComponents();
        this.facadeRegistrarEmpleado = new FacadeRegistrarEmpleado();
        this.usuario = usuario;

        Validador.validarSesion(usuario, this);
    }

    private void crearCuentaEmpleado() {
        // Cachamos los atributos ingresados en el formulario.
        String nombres = txtNombres.getText().trim();
        String apellidoP = txtApellidoP.getText().trim();
        String apellidoM = txtApellidoM.getText().trim();
        String telefono = txtTel.getText().trim();
        String curp = txtCurp.getText().trim();
        String rfc = txtRfc.getText().trim();
        String correo = txtCorreo.getText().trim();
        String contrasenia1 = new String(pwdContrasenia.getPassword()).trim();
        String contrasenia2 = new String(pwdConfirmarContrasenia.getPassword()).trim();
        String tipo = (String) cbxTipoEmpleado.getSelectedItem();
        // Obtener el índice del elemento seleccionado en el JComboBox
        int opcion = cbxTipoEmpleado.getSelectedIndex();

        // Actualizar el atributo Tipo dependiendo del elemento seleccionado
        switch (opcion) {
            case 0:
                tipo = "RRHH";
                break;
            case 1:
                tipo = "AACC";
                break;
            case 2:
                tipo = "PPMM";
                break;
            case 3:
                tipo = "GERE";
                break;
        }

        // Creamos una instancia del validador.
        Validador validador = new Validador();
        try {
            // Validamos cada dato.
            validador.validarNombres(nombres);
            validador.validarApellidoP(apellidoP);
            validador.validarApellidoM(apellidoM);
            validador.validarTelefono(telefono);
            validador.validarCURP(curp);
            validador.validarRFC(rfc);
            validador.validarCorreo(correo);
            validador.validarContrasenia(contrasenia1);
            validador.validarConfirmarContrasenia(contrasenia1, contrasenia2);

            // Creamos un usuario DTO con los datos introducidos.
            UsuarioDTO trabajador = new UsuarioDTO(nombres, apellidoP, apellidoM, telefono, curp, rfc, correo, contrasenia1, tipo);

            // Mandamos a crear la cuenta del usuario.
            facadeRegistrarEmpleado.crearCuenta(trabajador);

            // Limpiamos los campos.
            limpiarCampos();

            // Mensaje para indicar que el registro se completo correctamente.
            JOptionPane.showMessageDialog(this, "¡Empleado registrado con éxito!", "¡Yippee!", JOptionPane.INFORMATION_MESSAGE);
        } catch (PresentacionException | RegistrarEmpleadoException ex) {
            // Si se obtiene alguna excepción, imprimimos su mensaje.
            JOptionPane.showMessageDialog(this, ex.getMessage(), "¡Error!", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void limpiarCampos() {
        txtNombres.setText("");
        txtApellidoP.setText("");
        txtApellidoM.setText("");
        txtTel.setText("");
        txtCurp.setText("");
        txtRfc.setText("");
        txtCorreo.setText("");
        pwdContrasenia.setText("");
        pwdConfirmarContrasenia.setText("");
        cbxTipoEmpleado.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNombres = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtApellidoP = new javax.swing.JTextField();
        txtApellidoM = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTel = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCurp = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtRfc = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        pwdContrasenia = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pwdConfirmarContrasenia = new javax.swing.JPasswordField();
        cbxTipoEmpleado = new javax.swing.JComboBox<>();
        btnRegistrarEmpleado = new javax.swing.JButton();
        lblRegistrarEmpleado = new javax.swing.JLabel();
        lblSesion = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombres.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombresActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 270, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Nombres");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, -1, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Apellido Paterno");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, -1, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 102));
        jLabel11.setText("Rol");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 580, 200, 20));

        txtApellidoP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtApellidoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoPActionPerformed(evt);
            }
        });
        jPanel1.add(txtApellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 270, 40));

        txtApellidoM.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtApellidoM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoMActionPerformed(evt);
            }
        });
        jPanel1.add(txtApellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, 270, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Apellido Materno");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, -1, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Telefono");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 500, -1, 20));

        txtTel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelActionPerformed(evt);
            }
        });
        jPanel1.add(txtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 520, 270, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("CURP");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 570, -1, 30));

        txtCurp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCurp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCurpActionPerformed(evt);
            }
        });
        jPanel1.add(txtCurp, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 600, 270, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("RFC");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, -1, 20));

        txtRfc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtRfc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRfcActionPerformed(evt);
            }
        });
        jPanel1.add(txtRfc, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 280, 270, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("Correo");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 340, -1, 20));

        txtCorreo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 360, 270, 40));

        pwdContrasenia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pwdContrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdContraseniaActionPerformed(evt);
            }
        });
        jPanel1.add(pwdContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 440, 270, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("Contraseña");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 420, -1, 20));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setText("Confirmar contraseña");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 500, 200, 20));

        pwdConfirmarContrasenia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pwdConfirmarContrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdConfirmarContraseniaActionPerformed(evt);
            }
        });
        jPanel1.add(pwdConfirmarContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 520, 270, 40));

        cbxTipoEmpleado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbxTipoEmpleado.setForeground(new java.awt.Color(0, 102, 102));
        cbxTipoEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Recursos humanos", "Atención al cliente", "Personal de mantenimiento", "Gerente" }));
        jPanel1.add(cbxTipoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 600, 270, -1));

        btnRegistrarEmpleado.setBackground(new java.awt.Color(0, 102, 102));
        btnRegistrarEmpleado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegistrarEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarEmpleado.setText("Registrar");
        btnRegistrarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarEmpleadoActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 600, 130, 50));

        lblRegistrarEmpleado.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblRegistrarEmpleado.setText("Registrar empleado");
        lblRegistrarEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRegistrarEmpleadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRegistrarEmpleadoMouseExited(evt);
            }
        });
        jPanel1.add(lblRegistrarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 210, 90));

        lblSesion.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblSesion.setText("Cerrar sesión");
        lblSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSesionMouseExited(evt);
            }
        });
        jPanel1.add(lblSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 20, 150, 100));

        lblLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoMouseClicked(evt);
            }
        });
        jPanel1.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 230, 110));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoRegistrarEmpleado (1).png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 690));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 690));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtApellidoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoPActionPerformed
        crearCuentaEmpleado();
    }//GEN-LAST:event_txtApellidoPActionPerformed

    private void txtApellidoMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoMActionPerformed
        crearCuentaEmpleado();
    }//GEN-LAST:event_txtApellidoMActionPerformed

    private void txtCurpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCurpActionPerformed
        crearCuentaEmpleado();
    }//GEN-LAST:event_txtCurpActionPerformed

    private void txtRfcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRfcActionPerformed
        crearCuentaEmpleado();
    }//GEN-LAST:event_txtRfcActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        crearCuentaEmpleado();
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void txtNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombresActionPerformed
        crearCuentaEmpleado();
    }//GEN-LAST:event_txtNombresActionPerformed

    private void btnRegistrarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarEmpleadoActionPerformed
        crearCuentaEmpleado();
    }//GEN-LAST:event_btnRegistrarEmpleadoActionPerformed

    /**
     * Método que reacciona al evento de dar clic en el botón para ir a la
     * pantalla principal.
     *
     * @param evt Evento al que se escucha.
     */
    private void lblLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoMouseClicked
        try {
            FrmHomeTrabajador frmHomeTrabajador = new FrmHomeTrabajador(usuario);
            frmHomeTrabajador.setVisible(true);
        } catch (PresentacionException pe) {
            // Se muestra un mensaje si no se validó la sesión.
            JOptionPane.showMessageDialog(this, pe.getMessage(), "¡Error!", JOptionPane.ERROR_MESSAGE);
        }
        this.dispose();
    }//GEN-LAST:event_lblLogoMouseClicked

    /**
     * Método que reacciona al evento de dar clic en el botón para cerrar
     * sesión. Devuelve al usuario al login.
     *
     * @param evt Evento al que se escucha.
     */
    private void lblSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSesionMouseClicked
        FrmLogin frmLogin = new FrmLogin();
        frmLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblSesionMouseClicked

    /**
     * Método que reacciona al evento de pasar el mouse por encima del botón de
     * cerrar sesión y cambiar su color.
     *
     * @param evt Evento al que se escucha
     */
    private void lblSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSesionMouseEntered
        // TODO add your handling code here:
        lblSesion.setForeground(Color.GRAY);
    }//GEN-LAST:event_lblSesionMouseEntered

    /**
     * Método que reacciona al evento de que el mouse ya no esté sobre el botón
     * de cerrar sesión y cambiar su color.
     *
     * @param evt Evento al que se escucha
     */
    private void lblSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSesionMouseExited
        // TODO add your handling code here:
        lblSesion.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblSesionMouseExited

    /**
     * Método que reacciona al evento de que el mouse ya no esté sobre el botón
     * de registrar empleados y cambiar su color.
     *
     * @param evt Evento al que se escucha
     */
    private void lblRegistrarEmpleadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarEmpleadoMouseExited
        // TODO add your handling code here:
        lblRegistrarEmpleado.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblRegistrarEmpleadoMouseExited

    /**
     * Método que reacciona al evento de pasar el mouse por encima del botón de
     * registrar empleados y cambiar su color.
     *
     * @param evt Evento al que se escucha
     */
    private void lblRegistrarEmpleadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarEmpleadoMouseEntered
        // TODO add your handling code here:
        lblRegistrarEmpleado.setForeground(Color.GRAY);
        lblRegistrarEmpleado.setForeground(Color.GRAY);
    }//GEN-LAST:event_lblRegistrarEmpleadoMouseEntered

    private void txtTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelActionPerformed
        crearCuentaEmpleado();
    }//GEN-LAST:event_txtTelActionPerformed

    private void pwdContraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdContraseniaActionPerformed
        crearCuentaEmpleado();
    }//GEN-LAST:event_pwdContraseniaActionPerformed

    private void pwdConfirmarContraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdConfirmarContraseniaActionPerformed
        crearCuentaEmpleado();
    }//GEN-LAST:event_pwdConfirmarContraseniaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarEmpleado;
    private javax.swing.JComboBox<String> cbxTipoEmpleado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblRegistrarEmpleado;
    private javax.swing.JLabel lblSesion;
    private javax.swing.JPasswordField pwdConfirmarContrasenia;
    private javax.swing.JPasswordField pwdContrasenia;
    private javax.swing.JTextField txtApellidoM;
    private javax.swing.JTextField txtApellidoP;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtCurp;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtRfc;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables
}
